function ctrl=mpc_init(c)
assert(exist('fmincon','file')==2,'Install Optimization Toolbox.');
assert(sum(c.mpc.blocks)==c.mpc.horizon,'Move blocks must sum to horizon.');
ctrl.lastU=c.hover; ctrl.guess=zeros(4*numel(c.mpc.blocks),1);
ctrl.failures=0;
ctrl.options=optimoptions('fmincon','Algorithm','sqp','Display','off', ...
    'SpecifyObjectiveGradient',true,'SpecifyConstraintGradient',true, ...
    'MaxIterations',c.mpc.maxIterations,'MaxFunctionEvaluations',3000, ...
    'ConstraintTolerance',c.mpc.constraintTolerance, ...
    'OptimalityTolerance',c.mpc.optimalityTolerance,'StepTolerance',1e-8);
end
